version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  publish:
    executor: node/default
    steps:
      - run:
          command: echo "here goes your deploy steps"
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run deploy
          name: Deploy Extension

workflows:
  version: 2
  publish-extension:
    jobs:
      - publish:
          filters:
            tags:
              only: /^v.*/i
            branches:
              ignore: /.*/
