version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  tests:
    executor: node/default
    steps:
      - run:
          command: echo "here goes your test steps"
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: xvfb-run -a npm test
          name: Run tests

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - tests
